"""Initial migration

Revision ID: 5491d5af1515
Revises: 
Create Date: 2024-08-10 14:11:36.218826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5491d5af1515'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_local_file_id', table_name='local_file')
    op.drop_index('ix_local_file_path', table_name='local_file')
    op.drop_index('ix_local_file_status', table_name='local_file')
    op.drop_table('local_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_file',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_local_file_status', 'local_file', ['status'], unique=False)
    op.create_index('ix_local_file_path', 'local_file', ['path'], unique=1)
    op.create_index('ix_local_file_id', 'local_file', ['id'], unique=False)
    # ### end Alembic commands ###
