"""Add deletion_queued field to LocalFile model

Revision ID: dd02788742a9
Revises: 5491d5af1515
Create Date: 2024-08-10 14:13:19.934618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd02788742a9'
down_revision: Union[str, None] = '5491d5af1515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
